rosetta
cirruslabs/tart pull request #287
Opened 2022-10-25 20:52 UTC by siilats

the rosetta install is not implemented but it should add the share folder

2022-10-26 17:41 UTC, edigaryev commented
Hello Keith 👋

Thank you for your contribution! Could you please elaborate a bit on your use-case here and provide some concrete example of how this change solves it?

The reason I'm asking this is that "*Rosetta doesn’t support the bootstrapping or installation of Intel Linux distributions on Mac computers with Apple silicon using the Virtualization framework*" ([according to the official documentation](https://developer.apple.com/documentation/virtualization/running_intel_binaries_in_linux_vms_with_rosetta)), so this mechanism seems to be pretty limited to running specific Linux binaries, which Tart doesn't support currently, nor does your PR seem to provide support for.

2022-10-27 16:11 UTC, jonnybbb commented
In general having Rosetta support enabled will allow to run x86_64 applications inside the arm64 VM. See e.g [here](https://github.com/diddledani/macOS-Linux-VM-with-Rosetta#setting-up-rosetta). Also UTM supports enabling Rosetta see [here](https://docs.getutm.app/advanced/rosetta/).

2022-10-28 13:59 UTC, bootstraponline commented
Rosetta support & Linux clipboard sharing would be great for development purposes. A lot of binaries don't have native arm64 versions for Linux.

2022-11-02 12:06 UTC, edigaryev requested changes

2022-11-04 14:59 UTC, edigaryev commented
@siilats, to keep matters constructive, what do you think about only introducing the Rosetta-specific changes in this PR:

* the code chunk that calls `installRosetta()` (currently none) and the `installRosetta()` itself
* the code chunk that instantiates `VZLinuxRosettaDirectoryShare()` and adds it to the list of `directorySharingDevices`

This will greatly simplify and thus speed up the review process, and for the rest of the features — we can also introduce them into the codebase, but as separate PRs 🙌

2022-11-21 15:54 UTC, edigaryev commented
Closing in favor of https://github.com/cirruslabs/tart/pull/324.

2022-11-21 15:54 UTC, closed without merging

2022-11-21 17:05 UTC, siilats commented on Sources/tart/VM.swift
> +        configuration.directorySharingDevices.append(sharingDevice)
extra sharing device for the rosetta support